### ISSUE TITLE
missing lunarengine dependency

### ISSUE THREAD

**Issue by davince72** [Moon70/ParallelMultiverse#1]
Hi, 

Thanks for sharing your demo-code!! I tried to run it locally, but seems like a dependency is missing.
```
<dependency>
	<groupId>abyss</groupId>
	<artifactId>lunarengine</artifactId>
	<version>2.2</version>
</dependency>
```
Where can i find it?

**Comment by Moon70** [comment]
Hi,
this dependency is just beside the demo:
https://github.com/Moon70/LunarEngine
Maybe i should add some lines 'how to build', just give me a few minutes :-)

**Comment by Moon70** [comment]
Just added a short 'how to build' to the README, hope that helps.
Any more questions? Feel free to ask and i try to help if i can :-)

**Comment by davince72** [comment]
I'm sorry, compiles perfect now!
